name: license-lens CI
on: [push, pull_request]
jobs:
  selftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Make a tiny fixture and install one dep
        run: |
          mkdir -p fixtures/sample && cd fixtures/sample
          npm init -y >/dev/null
          npm i left-pad@1.3.0 --no-audit --no-fund
      - name: Run License Lens against the fixture
        run: |
          cd fixtures/sample
          node ../../bin/license-lens.mjs check
  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure publishable files are correct
        run: npm pack --dry-run
